"""add email column to user table.

Revision ID: d8aa5c11e562
Revises: 86831f3089e0
Create Date: 2026-04-27 23:55:14.366426

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d8aa5c11e562"
down_revision = "86831f3089e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
