"""Rename password to hashed_password.

Revision ID: 70327236b4c7
Revises: d8aa5c11e562
Create Date: 2026-04-28 00:50:16.944843

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70327236b4c7"
down_revision = "d8aa5c11e562"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("hashed_password", sa.String(length=200), nullable=False)
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_constraint(op.f("user_email_key"), "user", type_="unique")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_unique_constraint(
        op.f("user_email_key"), "user", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
