"""Enterprise structural update: models and constraints.

Revision ID: 116533e91ccd
Revises: ccd20d6f36c0
Create Date: 2026-04-27 13:08:13.019935

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "116533e91ccd"
down_revision = "ccd20d6f36c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_history")
    op.add_column(
        "saved_weather",
        sa.Column(
            "saved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "saved_weather",
        "city_name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_weather",
        "country",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("saved_weather_user_id_fkey"), "saved_weather", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "saved_weather", "user", ["user_id"], ["userid"], ondelete="CASCADE"
    )
    op.add_column("user", sa.Column("password", sa.String(length=200), nullable=False))
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "user", ["username"])
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "created_at")
    op.drop_column("user", "password")
    op.drop_constraint(None, "saved_weather", type_="foreignkey")
    op.create_foreign_key(
        op.f("saved_weather_user_id_fkey"),
        "saved_weather",
        "user",
        ["user_id"],
        ["userid"],
    )
    op.alter_column(
        "saved_weather",
        "country",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "saved_weather",
        "city_name",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("saved_weather", "saved_at")
    op.create_table(
        "search_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "city_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column(
            "searched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.userid"],
            name=op.f("search_history_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("search_history_pkey")),
    )
    # ### end Alembic commands ###
