"""Add search history table.

Revision ID: ccd20d6f36c0
Revises: 7f67c0f9ec06
Create Date: 2026-04-27 10:08:02.603623

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccd20d6f36c0"
down_revision = "7f67c0f9ec06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("city_name", sa.String(length=200), nullable=False),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.userid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_history")
    # ### end Alembic commands ###
